---
title: "CF_figs"
author: "Lizzy Schattle"
date: "12/5/2020"
output: html_document
---

These are the figures used in our final presentation and our final report. I made a dark grey version for the presentation slides and a white version for the report.

```{r setup, include=FALSE}
# packages
library(tidyverse)
library(ggplot2)
library(janitor)
library(tidyr)
```

1. Line Graph for Zonal Deforestation 2000-2019
```{r}
prop_loss <- read_csv("proportionalzonalloss.csv") %>% 
  rename(c("X1" = "protection_type"))

prop_loss <- prop_loss %>% 
  pivot_longer(!protection_type, names_to = "year", values_to = "perc_loss") %>% 
  group_by(protection_type)



# dark grey version for presentation
prop_loss %>% 
  ggplot(aes(x = year, y = perc_loss)) +
  geom_line(aes(group = protection_type,
                color = protection_type)) +
  scale_color_manual(values = c("goldenrod1", "black", "mediumseagreen", "snow3", "tomato1")) +
  theme_bw() +
  labs(x = "Year",
       y = "Proportion of Forest Lost") +
  theme(axis.title.x = element_text(color="gray80"),
        axis.title.y = element_text(color="gray80")) +
  theme(axis.text.x = element_text(angle=50, vjust=0.5, color = "gray80"), # put x axis dates at angle
        axis.text.y = element_text(color = "gray80")) +
  theme(axis.ticks.x = element_line(color = "gray80"),
        axis.ticks.y = element_line(color = "gray80"),
        axis.line = element_line(color = "gray80")) +
  theme(legend.title = element_blank()) +
  theme(legend.background = element_blank(),
        legend.key = element_rect(fill = NA), # get rid of those pesky gray boxes around legend items
        legend.text = element_text(color = "gray80")) +
  guides(colour = guide_legend(override.aes = list(size=1))) + # make the line colors show up bigger in the legend so you can tell what they are
  theme(panel.background = element_rect(fill = 'grey20'),
    panel.grid.major = element_line(size=0),
    panel.grid.minor = element_line(size=0)) +
  theme(plot.background = element_rect(fill = 'grey20'))


# white version for paper
prop_loss %>% 
  ggplot(aes(x = year, y = perc_loss)) +
  geom_line(aes(group = protection_type,
                color = protection_type),
            size = 1) +
  scale_color_manual(values = c("goldenrod1", "black", "mediumseagreen", "snow4", "tomato1")) +
  labs(x = "Year",
       y = "Proportion of Forest Lost") +
  theme_classic() +
  theme(axis.text.x = element_text(angle=50, vjust=0.5)) +
  theme(legend.key = element_rect(fill = NA, color = NA)) +
   theme(legend.title = element_blank())


# now as a bar chart with totals over all years
prop_loss %>% 
  ggplot(aes(x = reorder(protection_type, perc_loss),
             y = perc_loss)) +
  geom_bar(stat = "identity", aes(color = protection_type,
                                  fill = protection_type)) +
   scale_fill_manual(values = c("goldenrod1",
                                "black",
                                "mediumseagreen",
                                "snow4",
                                "tomato1")) +
  scale_color_manual(values = c("goldenrod1",
                                "black",
                                "mediumseagreen",
                                "snow4",
                                "tomato1")) +
  theme_classic() +
  theme(legend.position = "none") +
   labs(x = "Protection Type",
       y = "Total Proportion of Forest Lost") +
  scale_y_continuous(expand = c(0, 0)) # to make the bar graph start at the origin

```

2. Bar Graph for CF (Granted and In Process) from 2016 to 2019
```{r}
cf_loss <- read_csv("cf_2016to2019.csv") %>% 
  na.omit() %>% 
  rename(c("Protection Type" = "protection_type"))

cf_loss <- cf_loss %>% 
  pivot_longer(!protection_type, names_to = "year", values_to = "perc_loss")


bar_plot_df <- data.frame(cf_status = c("in_process", "granted"),
                          perc_loss = c(0.013781929, 0.015821567)) # from GEE


# dark grey version for presentation
ggplot(data = bar_plot_df, mapping = aes(x = cf_status,
                                         y = perc_loss)) +
  geom_col(aes(fill = cf_status)) +
  scale_fill_manual(values = c("mediumseagreen", "goldenrod1")) +
  theme_bw() +
  labs(x = "CF Status",
       y = "Percent Loss (2016 - 2019)") +
  scale_x_discrete(labels = c("Granted", "In Process")) +
  theme(axis.title.x = element_text(color="gray80"),
        axis.title.y = element_text(color="gray80")) + 
   theme(axis.text.x = element_text(color = "gray80"),
        axis.text.y = element_text(color = "gray80")) +
  theme(axis.ticks.x = element_line(color = "gray80"),
        axis.ticks.y = element_line(color = "gray80"),
        axis.line = element_line(color = "gray80")) +
  theme(legend.position = "none") +
  theme(panel.background = element_rect(fill = 'grey20'),
    panel.grid.major = element_line(size=0),
    panel.grid.minor = element_line(size=0)) +
  theme(plot.background = element_rect(fill = 'grey20'))

# white version for paper
ggplot(data = bar_plot_df, mapping = aes(x = cf_status,
                                         y = perc_loss)) +
  geom_col(aes(fill = cf_status), width = 0.6) +
  scale_y_continuous(expand = c(0, 0)) +
  scale_fill_manual(values = c("mediumseagreen", "goldenrod1")) +
  labs(x = "CF Status",
       y = "Percent Loss (2016 - 2019)") +
  scale_x_discrete(labels = c("Granted", "In Process")) +
  geom_text(aes(label = round(perc_loss, 4)), size = 3, hjust = 0.5, vjust = 3) +
  theme_classic() +
  theme(legend.position = "none")
```

3. Regional bar graphs comparing East CFs and West CFs
```{r}
regional_df <- data.frame(Region = c("W. Province Loss", "W. Province Gain", "W. CF Loss", "W. CF Gain", "E. Province Loss", "E. Province Gain","E. CF Loss", "E. CF Gain"),
                          Change = c(0.0578, 0.0043, 0.0322, 0.0052, 0.0826, 0.0123, 0.103, 0.0072))

regional_df$Region <- factor(regional_df$Region, levels = c("W. Province Loss", "W. Province Gain", "W. CF Loss", "W. CF Gain", "E. Province Loss", "E. Province Gain","E. CF Loss", "E. CF Gain"))


# dark grey version for presentation
ggplot(data = regional_df, 
       mapping = aes(x = Region,
                     y = Change)) +
  geom_col(aes(fill = Region)) +
   scale_fill_manual(values = c("cyan4", "darkslategray", "cyan4", "darkslategray", "navajowhite", "navajowhite4", "navajowhite", "navajowhite4")) +
   theme_bw() +
  labs(x = "West                                                                 East",
       y = "Percent Loss (2000 - 2019)") +
  scale_x_discrete(labels = c("Total Loss", "Total Gain", "CF Loss", "CF Gain", "Total Loss", "Total Gain", "CF Loss", "CF Gain")) +
  theme(axis.title.x = element_text(color = "gray80"),
        axis.title.y = element_text(color="gray80")) + 
   theme(axis.text.x = element_text(vjust=0.5, color = "gray80"),
        axis.text.y = element_text(color = "gray80")) +
  theme(axis.ticks.x = element_line(color = "gray80"),
        axis.ticks.y = element_line(color = "gray80"),
        axis.line = element_line(color = "gray80")) +
  theme(legend.position = "none") +
  theme(panel.background = element_rect(fill = 'grey20'),
    panel.grid.major = element_line(size=0),
    panel.grid.minor = element_line(size=0)) +
  theme(plot.background = element_rect(fill = 'grey20'))


# white version for paper
ggplot(data = regional_df, 
       mapping = aes(x = Region,
                     y = Change)) +
  geom_col(aes(fill = Region)) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, 0.11)) +
   scale_fill_manual(values = c("cyan4", "darkslategray", "cyan4", "darkslategray", "navajowhite3", "navajowhite4", "navajowhite3", "navajowhite4")) +
  labs(x = "West                                                                 East",
       y = "Percent Loss (2000 - 2019)") +
  scale_x_discrete(labels = c("Total Loss", "Total Gain", "CF Loss", "CF Gain", "Total Loss", "Total Gain", "CF Loss", "CF Gain")) +
  theme(axis.title.x = element_text(vjust = -1)) +
   theme(axis.text.x = element_text(vjust = 0.5)) +
  theme(legend.position = "none") +
  geom_text(aes(label = round(Change, 3)), size = 3, hjust = 0.5, vjust = -0.5) +
  theme_classic() +
  theme(legend.position = "none")
```





